### ISSUE TITLE
Urban Wind Field: Urock v2023a stuck or error

### ISSUE THREAD

**Issue by Lalalashp** [UMEP-dev/UMEP#715]
Hello!

I'm still having trubles with the urban wind field processor.
This time i tried to restart the analysis from scratch but it resolted in more problems.
The first issue i found was that the proces started but it gets stuck on the last iteration, as you can see from the script contained in 'ERRORI'-->'140_stuck-02_27'. For now, the problem happen for the areas '101' and '140'. 

The second one is an error i already reported here https://github.com/UMEP-dev/UMEP/discussions/700 , but still haven't found a solution yet. I reported the errors in the folder 'ERRORI', which happend for the 128, 129 and 135 area so far.

I'm operating with the last version of UMEP from the repository and 16gb of RAM.
I'm attaching the dataset divided in two with the files inside.

[dataset 2.zip](https://github.com/user-attachments/files/19010940/dataset.2.zip)
[dataset.zip](https://github.com/user-attachments/files/19010921/dataset.zip)

Do you know what i can do to make it work?
Thanks in advance,
Laura

**Comment by j3r3m1** [comment]
Hi and thank you for reporting. It seems the first error is related in a way to the one meet here: https://github.com/UMEP-dev/UMEP/issues/704
The error you report seems to be a new case but still related to the same problem of interpolation of the result (conversion from vector to raster). I could not have time to investigate but none of the rasterio or QGIS IDW interpolations end with good results. However, it seems to work with the solution proposed at https://github.com/UMEP-dev/UMEP/issues/704#issuecomment-2640540554. Can you please have a try for the cases that do not work. 

Concerning your second error, I have identified and solved the issue in the last UMEP version. The problem happened only when there was several layers of vegetation. This should not happen anymore. Please report also for this case.

**Comment by j3r3m1** [comment]
Any update for these 2 issues ?
If not you can try with the last version it should now work.

**Comment by Lalalashp** [comment]
hello!
i tried the last verision of UMEP and for two areas it worked perfectly, but for other two i still get the first error. I'm gonna try to make the areas even smaller and get back to you!

**Comment by j3r3m1** [comment]
I close this thread since it is the same error as in #704 (you can provide further info directly there)
