### ISSUE TITLE
Urock complex geometry

### ISSUE THREAD

**Issue by lgzdbf** [UMEP-dev/UMEP#732]
Hello,

Following post #704, I am creating the issue ticket here.
The building geometries come from the IGN and are quite common in many south neighborhoods in Grenoble. I previously standardized the geometries using Urock prepare.

Thanks in advance :)

**Comment by j3r3m1** [comment]
Thank you for reporting. Here is the content of the initial message.



I am not sure if this is the same kind of issue we have encountered before, but it looks similar. On a tile with a high number of buildings, Urock runs indefinitely. However, this time the issue doesn't seem to be with the interpolation registration, but rather with the creation of the Rockle zones. I am attaching the inputs for the tile that is causing the problem, and below the logs : 

[gre_c-410_test.zip](https://github.com/user-attachments/files/19848075/gre_c-410_test.zip)


Linux terminal : 
Load input data
Load table 'build_pre_srid_20250422082607'
Load table 'veg_pre_srid_20250422082607'
Creates blocks and stacked blocks
Rotates geometries from 200.257904 degrees
Identify block base height and block cavity base
Calculates obstacle properties
Calculates zone properties
Initializes upwind facades
Update upwind facades base height
Initializes downwind facades
Calculates study area properties
Rotates geometries from -200.257904 degrees
Creates displacement zones
Creates cavity and wake zones

qgis : 
Writing settings for this model run to specified output folder (Filename: RunInfoURock_YYYY_DOY_HHMM.txt)
Initiating algorithm
Creates an H2GIS Instance and load data
Creates the stacked blocks used as obstacles
Rotates obstacles to the right direction and calculates geometry properties
Roughness zone properties are:

- z0: 2.5556335094103626
- d: 16.99496283757891
- Hr: 17.037556729402418
- H_ob_max: 54.0
- lambda_f: 1
Creates the 2D Röckle zones

**Comment by j3r3m1** [comment]
And the issue should be solved using the last version of URock. Please feel free to reopen if not.

**Comment by lgzdbf** [comment]
Ok perfect, thanks, it works, but there is still an error on the other tiles when there is no building data, as reported here #726.
(I don't have permission to reopen tickets.)
